apiVersion: v1
kind: PersistentVolume
metadata:
  name: rna-seq-web-pv
spec:
  capacity:
      storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  gcePersistentDisk:
    fsType: ext4
    pdName: rna-seq-web-disk
  mountOptions:
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rna-seq-web-pv-rna-seq-web-backend-0
spec:
  storageClassName: ""
  volumeName: rna-seq-web-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
